### ISSUE TITLE
installation of diffusion_analysis 

### ISSUE THREAD

**Issue by MJ-learner** [tylerjereddy/diffusion_analysis_MD_simulations#4]
Kindly let me know how to add diffusion_analysis module , as there is no setup.py file or make install.

**Comment by tylerjereddy** [comment]
At the moment I would suggest using `git clone` to copy the repository to a convenient location and then adding that path to your `PYTHONPATH`. For example:

```
import sys
sys.path.append('/path/to/diffusion_analysis/')
import diffusion_analysis
```
You are correct that there's no standard way to 'install' the module at the moment. I suppose I could try to write a simple `setup.py` script following some of the [instructions](https://docs.python.org/2/distutils/introduction.html#distutils-simple-example). Feel free to work on that if you like!

**Comment by MJ-learner** [comment]
Thank you for your reply...

**Comment by tylerjereddy** [comment]
A simple Distutils `setup.py` script has been added to the package, allowing for easy installation of the module.
